#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile pipenv "$@"
  local pth_asciinema="$(pipenv run which asciinema)"
  mkdir -p "$shome/bin"
  ln -nfs "$pth_asciinema" "$shome/bin/"
}

main "$@"
